config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :messages, except: :show

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true

  # broadcast with Turbo Streams
  broadcasts inserts_by: :prepend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :set_message, except: [:index, :new, :create]

  def index
    @messages = Message.all.order(:id, :desc)
  end

  def new
    @message = Message.new
  end

  def edit
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      @message = Message.new
      render :new
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @message.update(message_params)
      render :edit
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @message.destroy
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboStreamPr1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# hack for popperjs error: https://github.com/rails/importmap-rails/issues/65#issuecomment-999939960 %>
    <script>window.process = {env: {}}</script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for message do |form| %>
  <%= form.error_notification %>

  <%= form.input :content %>
  <%= form.button :submit, class: "btn-primary" %>
<% end %>

app/views/messages/_message.html.erb
<%= turbo_stream_from message %>

<div class="card my-2" id="<%= dom_id message %>">
  <div class="card-header">
    <%= l message.created_at %>
  </div>
  <div class="card-body">
    <%= message.content %>
    <%= turbo_frame_tag dom_id(message, :edit) %>
  </div>
  <div class="card-footer">
    <%= link_to "Edit", edit_message_path(message), data: { turbo_frame: dom_id(message, :edit) } %>
    <%= link_to "Destroy", message_path(message), data: { turbo_method: :delete } %>
  </div>
</div>

app/views/messages/edit.html.erb
<%= turbo_frame_tag dom_id(@message, :edit) do %>
  <%= render "form", message: @message %>
<% end %>

app/views/messages/index.html.erb
<%= turbo_stream_from :messages %>

<h3>Messages</h3>

<div class="card my-2">
  <div class="card-body">
    <%= turbo_frame_tag :new_message, src: new_message_path, loading: :lazy %>
  </div>
</div>

<div id="messages">
  <%= render @messages %>
</div>

app/views/messages/new.html.erb
<%= turbo_frame_tag :new_message do %>
  <%= render "form", message: @message %>
<% end %>